# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=10240']      #  where large means 10MB+, as in Hugging Face's git server
    - id: debug-statements         # check for python debug statements (import pdb, breakpoint, etc.)
    - id: detect-private-key       # checks for private keys (BEGIN X PRIVATE KEY, etc.)

  # black python autoformatting

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
    # additional configuration of black in pyproject.toml

# flake8 python linter with all the fixins
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-annotations, flake8-bandit, flake8-bugbear, flake8-black, flake8-docstrings,
          flake8-import-order, darglint, mypy, pycodestyle, pydocstyle]
        args: ["--config", ".flake8", "src/"]
    # additional configuration of flake8 and extensions in .flake8

# shellcheck-py for linting shell files
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
